/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import '@ionic/core';
import 'ionicons';
import {
  MatchResults,
} from '@stencil/router';
import {
  EventEmitter,
} from '@stencil/core';


export namespace Components {

  interface AppClient {}
  interface AppClientAttributes extends StencilHTMLAttributes {}

  interface AppContact {}
  interface AppContactAttributes extends StencilHTMLAttributes {}

  interface AppDocuments {}
  interface AppDocumentsAttributes extends StencilHTMLAttributes {}

  interface AppFacebookvideo {}
  interface AppFacebookvideoAttributes extends StencilHTMLAttributes {}

  interface AppFooter {}
  interface AppFooterAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppPhoto {}
  interface AppPhotoAttributes extends StencilHTMLAttributes {}

  interface AppPresentationText {}
  interface AppPresentationTextAttributes extends StencilHTMLAttributes {}

  interface AppPresentation {}
  interface AppPresentationAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppProjectInfos {
    'Id': string;
  }
  interface AppProjectInfosAttributes extends StencilHTMLAttributes {
    'Id'?: string;
  }

  interface AppProjectsGallery {}
  interface AppProjectsGalleryAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppTitle {}
  interface AppTitleAttributes extends StencilHTMLAttributes {}

  interface LazyImg {
    'alt': string;
    'src': string;
  }
  interface LazyImgAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
    'src'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppClient': Components.AppClient;
    'AppContact': Components.AppContact;
    'AppDocuments': Components.AppDocuments;
    'AppFacebookvideo': Components.AppFacebookvideo;
    'AppFooter': Components.AppFooter;
    'AppHome': Components.AppHome;
    'AppPhoto': Components.AppPhoto;
    'AppPresentationText': Components.AppPresentationText;
    'AppPresentation': Components.AppPresentation;
    'AppProfile': Components.AppProfile;
    'AppProjectInfos': Components.AppProjectInfos;
    'AppProjectsGallery': Components.AppProjectsGallery;
    'AppRoot': Components.AppRoot;
    'AppTitle': Components.AppTitle;
    'LazyImg': Components.LazyImg;
  }

  interface StencilIntrinsicElements {
    'app-client': Components.AppClientAttributes;
    'app-contact': Components.AppContactAttributes;
    'app-documents': Components.AppDocumentsAttributes;
    'app-facebookvideo': Components.AppFacebookvideoAttributes;
    'app-footer': Components.AppFooterAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-photo': Components.AppPhotoAttributes;
    'app-presentation-text': Components.AppPresentationTextAttributes;
    'app-presentation': Components.AppPresentationAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-project-infos': Components.AppProjectInfosAttributes;
    'app-projects-gallery': Components.AppProjectsGalleryAttributes;
    'app-root': Components.AppRootAttributes;
    'app-title': Components.AppTitleAttributes;
    'lazy-img': Components.LazyImgAttributes;
  }


  interface HTMLAppClientElement extends Components.AppClient, HTMLStencilElement {}
  var HTMLAppClientElement: {
    prototype: HTMLAppClientElement;
    new (): HTMLAppClientElement;
  };

  interface HTMLAppContactElement extends Components.AppContact, HTMLStencilElement {}
  var HTMLAppContactElement: {
    prototype: HTMLAppContactElement;
    new (): HTMLAppContactElement;
  };

  interface HTMLAppDocumentsElement extends Components.AppDocuments, HTMLStencilElement {}
  var HTMLAppDocumentsElement: {
    prototype: HTMLAppDocumentsElement;
    new (): HTMLAppDocumentsElement;
  };

  interface HTMLAppFacebookvideoElement extends Components.AppFacebookvideo, HTMLStencilElement {}
  var HTMLAppFacebookvideoElement: {
    prototype: HTMLAppFacebookvideoElement;
    new (): HTMLAppFacebookvideoElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppPhotoElement extends Components.AppPhoto, HTMLStencilElement {}
  var HTMLAppPhotoElement: {
    prototype: HTMLAppPhotoElement;
    new (): HTMLAppPhotoElement;
  };

  interface HTMLAppPresentationTextElement extends Components.AppPresentationText, HTMLStencilElement {}
  var HTMLAppPresentationTextElement: {
    prototype: HTMLAppPresentationTextElement;
    new (): HTMLAppPresentationTextElement;
  };

  interface HTMLAppPresentationElement extends Components.AppPresentation, HTMLStencilElement {}
  var HTMLAppPresentationElement: {
    prototype: HTMLAppPresentationElement;
    new (): HTMLAppPresentationElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppProjectInfosElement extends Components.AppProjectInfos, HTMLStencilElement {}
  var HTMLAppProjectInfosElement: {
    prototype: HTMLAppProjectInfosElement;
    new (): HTMLAppProjectInfosElement;
  };

  interface HTMLAppProjectsGalleryElement extends Components.AppProjectsGallery, HTMLStencilElement {}
  var HTMLAppProjectsGalleryElement: {
    prototype: HTMLAppProjectsGalleryElement;
    new (): HTMLAppProjectsGalleryElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTitleElement extends Components.AppTitle, HTMLStencilElement {}
  var HTMLAppTitleElement: {
    prototype: HTMLAppTitleElement;
    new (): HTMLAppTitleElement;
  };

  interface HTMLLazyImgElement extends Components.LazyImg, HTMLStencilElement {}
  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };

  interface HTMLElementTagNameMap {
    'app-client': HTMLAppClientElement
    'app-contact': HTMLAppContactElement
    'app-documents': HTMLAppDocumentsElement
    'app-facebookvideo': HTMLAppFacebookvideoElement
    'app-footer': HTMLAppFooterElement
    'app-home': HTMLAppHomeElement
    'app-photo': HTMLAppPhotoElement
    'app-presentation-text': HTMLAppPresentationTextElement
    'app-presentation': HTMLAppPresentationElement
    'app-profile': HTMLAppProfileElement
    'app-project-infos': HTMLAppProjectInfosElement
    'app-projects-gallery': HTMLAppProjectsGalleryElement
    'app-root': HTMLAppRootElement
    'app-title': HTMLAppTitleElement
    'lazy-img': HTMLLazyImgElement
  }

  interface ElementTagNameMap {
    'app-client': HTMLAppClientElement;
    'app-contact': HTMLAppContactElement;
    'app-documents': HTMLAppDocumentsElement;
    'app-facebookvideo': HTMLAppFacebookvideoElement;
    'app-footer': HTMLAppFooterElement;
    'app-home': HTMLAppHomeElement;
    'app-photo': HTMLAppPhotoElement;
    'app-presentation-text': HTMLAppPresentationTextElement;
    'app-presentation': HTMLAppPresentationElement;
    'app-profile': HTMLAppProfileElement;
    'app-project-infos': HTMLAppProjectInfosElement;
    'app-projects-gallery': HTMLAppProjectsGalleryElement;
    'app-root': HTMLAppRootElement;
    'app-title': HTMLAppTitleElement;
    'lazy-img': HTMLLazyImgElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
